version: '2'

services:
  scylladb-01:
    image: scylladb/scylla-enterprise:2021.1.8
    networks:
      scylla_net:
        ipv4_address: 172.19.0.2
    container_name: scylladb-01
    hostname: scylladb-01
    command: "--seeds 172.19.0.2 --cpuset 1,5 --memory 1G --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-02:
    image: scylladb/scylla-enterprise:2021.1.8
    networks:
      scylla_net:
        ipv4_address: 172.19.0.3
    container_name: scylladb-02
    hostname: scylladb-02
    command: "--seeds 172.19.0.2 --cpuset 2,6 --memory 3G --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

  scylladb-03:
    image: scylladb/scylla-enterprise:2021.1.8
    networks:
      scylla_net:
        ipv4_address: 172.19.0.4
    container_name: scylladb-03
    hostname: scylladb-03
    command: "--seeds 172.19.0.2 --cpuset 3,7 --memory 3G --developer-mode 1 --api-address 127.0.0.1"
    cap_add:
      - SYS_NICE

networks:
  scylla_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1
